apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: sunalpha
  namespace: iplonapis
spec:
  stripPrefix:
    forceSlash: false
    prefixes:
      - /sunalpha
      - /chitthoor